<a href="https://colab.research.google.com/github/MANMOHAN04/manmohan/blob/main/Numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [ ]:
#Numpy: Fundamental package of scientific  computing
import numpy as np

#1D array are known as vector
x =np.array([1,3,5,7,9])
x

array([1, 3, 5, 7, 9])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
# 2D array also known as Matrix

y= np.array([[1,2,3,4,5],[3,5,7,9,11]])
y


array([[ 1,  2,  3,  4,  5],
       [ 3,  5,  7,  9, 11]])

In [ ]:
type(y)

numpy.ndarray

In [ ]:
#3D array also known as tensor
z=np.array([[[12,14,16],[16,18,20],[20,22,24]]],dtype=float)
z

array([[[12., 14., 16.],
        [16., 18., 20.],
        [20., 22., 24.]]])

In [ ]:
#arane
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#reshape
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np.arange(36).reshape(2,3,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]]])

In [ ]:
#np.ones are used for initialized the value
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#np.zeros
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((2,2))

array([[0.38904594, 0.87367719],
       [0.1774415 , 0.01544487]])

In [ ]:
#np.linspace
np.linspace(-10,20,10)

array([-10.        ,  -6.66666667,  -3.33333333,   0.        ,
         3.33333333,   6.66666667,  10.        ,  13.33333333,
        16.66666667,  20.        ])

In [ ]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Attributes of Numpy

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
#size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
#itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


#Changing Datatype

In [ ]:
#astype
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#1.Scalar Operations

#Arithmatics
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a2+4

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [ ]:
#relational Operations
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#2.Vector Operations

#Arithmatics Operation

a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

#Array Function

In [ ]:
a1=np.random.random((3,3))
a1

array([[0.02032613, 0.39852991, 0.12255184],
       [0.31465615, 0.42065188, 0.72397592],
       [0.09799936, 0.38807804, 0.85360249]])

In [ ]:
a1=np.round(a1*100)
a1

array([[ 2., 40., 12.],
       [31., 42., 72.],
       [10., 39., 85.]])

In [ ]:
#max/min/sum/prod
print(np.max(a1, axis =1)) #axis=1 means row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))


[40. 72. 85.]
85.0
2.0
333.0
2983309056000.0


In [ ]:
 #mean,median,std,var
print(np.mean(a1,axis=0))
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

[14.33333333 40.33333333 56.33333333]
37.0
39.0
26.20856518180438
686.8888888888889


In [ ]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exp
print(np.log(a1))

print(np.exp(a1))

[[0.69314718 3.68887945 2.48490665]
 [3.4339872  3.73766962 4.27666612]
 [2.30258509 3.66356165 4.44265126]]
[[7.38905610e+00 2.35385267e+17 1.62754791e+05]
 [2.90488497e+13 1.73927494e+18 1.85867175e+31]
 [2.20264658e+04 8.65934004e+16 8.22301271e+36]]


In [ ]:
#round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[15., 78., 53.],
       [77., 90., 86.]])

#Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2[0][3]

3.0

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1][0][1]

5

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2[0,:]

array([0., 1., 2., 3.])

In [ ]:
a2[:,2]

array([ 2.,  6., 10.])

In [ ]:
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [ ]:
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [ ]:
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [ ]:
a2[1,::3]

array([4., 7.])

In [ ]:
a2[:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [ ]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

#Iterating

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping- Transpose,Ravel

In [ ]:
#Transpose
np.transpose(a3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [ ]:
#ravel
a2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

#Stacking -vstack,hstack

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Spliting:- hsplit,vsplit

In [ ]:
np.hsplit(a2,2)

[array([[0., 1.],
        [4., 5.],
        [8., 9.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])]

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]