<a href="https://colab.research.google.com/github/MANMOHAN04/manmohan/blob/main/Numpy_Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#np.sort

In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(1,100,15)
a

array([80, 66, 33,  5, 12, 87, 44, 65,  3, 15, 66, 83, 12, 60, 60])

In [ ]:
np.sort(a) #[::-1] are used to sort in desending order

array([ 1,  2, 21, 26, 26, 28, 40, 44, 53, 72, 74, 80, 83, 86, 99])

In [ ]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[ 6, 60, 27, 17],
       [59, 72, 23, 14],
       [98, 38,  7, 34],
       [ 8, 83, 56, 80],
       [45, 90, 43, 26],
       [25, 70,  2, 90]])

In [ ]:
np.sort(b)

array([[14, 17, 21, 71],
       [ 7, 21, 26, 99],
       [12, 15, 33, 59],
       [65, 75, 91, 95],
       [57, 60, 75, 86],
       [ 7, 25, 56, 92]])

#np.append

In [ ]:
np.append(a,200)

array([ 83,  21,  44,  26,  72,   1,  86,  99,  40,  28,   2,  26,  80,
        74,  53, 200])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[21., 14., 17., 71.,  1.],
       [26.,  7., 99., 21.,  1.],
       [59., 12., 33., 15.,  1.],
       [95., 65., 91., 75.,  1.],
       [60., 86., 75., 57.,  1.],
       [ 7., 92., 25., 56.,  1.]])

#np.concatenate

In [ ]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#np.unique

In [ ]:
e=np.array([1,2,1,2,3,1,2,3,4,2,3,4,5,3,4,5,6])
e

array([1, 2, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#np.expand_dims

In [ ]:
np.expand_dims(a,axis=0)

array([[83, 21, 44, 26, 72,  1, 86, 99, 40, 28,  2, 26, 80, 74, 53]])

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

#np.where

In [ ]:
a

array([ 4, 25, 85, 64, 79, 98, 47, 34, 16, 68, 23, 39, 96, 63, 88])

In [ ]:
#find all indexes whose values are greater than 50
np.where(a>50)

(array([ 2,  3,  4,  5,  9, 12, 13, 14]),)

In [ ]:
#replace all the values which are greater >50 with 0
np.where(a>50,0,a)

array([ 4, 25,  0,  0,  0,  0, 47, 34, 16,  0, 23, 39,  0,  0,  0])

In [ ]:
#replace all even no. with 0
np.where(a%2==0,0,a)

array([ 0, 25, 85,  0, 79,  0, 47,  0,  0,  0, 23, 39,  0, 63,  0])

#np.argmax

In [ ]:
a

array([39, 84, 31, 30,  1, 89, 88, 87, 69, 64, 67, 71, 64, 45, 84])

In [ ]:
np.argmax(a)   #argmax are used to find index of a max no

5

In [ ]:
b

array([[57,  9, 86, 33],
       [56, 29, 80, 12],
       [84, 28, 11, 80],
       [73, 91, 32, 80],
       [40, 74, 71, 28],
       [23, 48, 57, 93]])

In [ ]:
np.argmax(b,axis=1)

array([2, 2, 0, 1, 1, 3])

#np.argmin

In [ ]:
np.argmin(a)

4

#np.cumsum

In [ ]:
a

array([39, 84, 31, 30,  1, 89, 88, 87, 69, 64, 67, 71, 64, 45, 84])

In [ ]:
np.cumsum(a)

array([ 39, 123, 154, 184, 185, 274, 362, 449, 518, 582, 649, 720, 784,
       829, 913])

In [ ]:
np.cumsum(b,axis=1)

array([[ 57,  66, 152, 185],
       [ 56,  85, 165, 177],
       [ 84, 112, 123, 203],
       [ 73, 164, 196, 276],
       [ 40, 114, 185, 213],
       [ 23,  71, 128, 221]])

#np.cumprod

In [ ]:
np.cumprod(a)

array([                  39,                 3276,               101556,
                    3046680,              3046680,            271154520,
                23861597760,        2075959005120,      143241171353280,
           9167434966609920,   614218142762864640,  6715999988744286208,
        5548885584314630144, -8554565737775366144,   839496901541756928])

#np.percentile

In [ ]:
a

array([39, 84, 31, 30,  1, 89, 88, 87, 69, 64, 67, 71, 64, 45, 84])

In [ ]:
np.percentile(a,100)

89.0

In [ ]:
np.percentile(a,50)

67.0

#np.histogram

In [ ]:
a

array([39, 84, 31, 30,  1, 89, 88, 87, 69, 64, 67, 71, 64, 45, 84])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 0, 0, 3, 1, 0, 4, 1, 5, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

#np.corrcoef

In [ ]:
salary=np.array([20000,35000,50000,60000,71100])
experience=np.array([1,2,3,1,4])

np.corrcoef(salary,experience)


array([[1.        , 0.61691121],
       [0.61691121, 1.        ]])

#np.isin

In [ ]:
a

array([80, 66, 33,  5, 12, 87, 44, 65,  3, 15, 66, 83, 12, 60, 60])

In [ ]:
items = [12,15,20,50,80,46,89,38]

np.isin(a,items)

array([ True, False, False, False,  True, False, False, False, False,
        True, False, False,  True, False, False])

In [ ]:
a[np.isin(a,items)]

array([80, 12, 15, 12])

#np.flip

In [ ]:
a

array([80, 66, 33,  5, 12, 87, 44, 65,  3, 15, 66, 83, 12, 60, 60])

In [ ]:
np.flip(a)

array([60, 60, 12, 83, 66, 15,  3, 65, 44, 87, 12,  5, 33, 66, 80])

#np.put

In [ ]:
a

array([80, 66, 33,  5, 12, 87, 44, 65,  3, 15, 66, 83, 12, 60, 60])

In [ ]:
np.put(a,[1,5],[65,97]) #np.put do permanent change

In [ ]:
a

array([80, 65, 33,  5, 12, 97, 44, 65,  3, 15, 66, 83, 12, 60, 60])

#np.delete

In [ ]:
np.delete(a,[2,4,14,5])

array([80, 65,  5, 44, 65,  3, 15, 66, 83, 12, 60])

In [ ]:
a

array([80, 65, 33,  5, 12, 97, 44, 65,  3, 15, 66, 83, 12, 60, 60])

#Set Functions


*   np.union1d
*   np.intersect1d


*   np.setdiff1d
*   np.setxor1d

*   np.in1d







In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,n)

array([False, False,  True,  True,  True])

In [ ]:
n[np.in1d(n,m)]

array([3, 4, 5])

#np.clip

In [ ]:
a

array([80, 65, 33,  5, 12, 97, 44, 65,  3, 15, 66, 83, 12, 60, 60])

In [ ]:
np.clip(a,a_min=15,a_max=50)

array([50, 50, 33, 15, 15, 50, 44, 50, 15, 15, 50, 50, 15, 50, 50])